name: Ruby on Rails CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bundle
        run: sudo gem install bundler:1.17.2
      - name: Install bundler
        run: |
          cd server
          bundle install
      - name: Rubocop
        run: cd server && bundle exec rubocop
      - name: Rails Best Practices
        run: cd server && bundle exec rails_best_practices -e "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rpec
        run: cd server && bundle exec rspec --format documentation
      - name: reek
        run: cd server && bundle exec reek
